root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/cohi-api"
  cmd = "go build -o ./tmp/cohi-api ./cmd/api"
  delay = 200
  exclude_dir = ["tmp", "bin", "vendor", "references", "deployments"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "sql"]
  kill_delay = "2s"
  send_interrupt = true
  stop_on_error = true

[log]
  time = true

[misc]
  clean_on_exit = true
